/*
 * Spring Boot使用 Swagger2 构建RestFul API
 * 接口文档
 *
 * OpenAPI spec version: v1
 * Contact: 123456@dongfangdi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bidewu.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ApiDropHouseRentDO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-26T06:55:57.895Z")
public class ApiDropHouseRentDO {
  @SerializedName("city")
  private String city = null;

  @SerializedName("cityId")
  private Integer cityId = null;

  @SerializedName("company")
  private String company = null;

  @SerializedName("sourceHouseId")
  private String sourceHouseId = null;

  public ApiDropHouseRentDO city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @ApiModelProperty(value = "")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public ApiDropHouseRentDO cityId(Integer cityId) {
    this.cityId = cityId;
    return this;
  }

   /**
   * Get cityId
   * @return cityId
  **/
  @ApiModelProperty(value = "")
  public Integer getCityId() {
    return cityId;
  }

  public void setCityId(Integer cityId) {
    this.cityId = cityId;
  }

  public ApiDropHouseRentDO company(String company) {
    this.company = company;
    return this;
  }

   /**
   * Get company
   * @return company
  **/
  @ApiModelProperty(value = "")
  public String getCompany() {
    return company;
  }

  public void setCompany(String company) {
    this.company = company;
  }

  public ApiDropHouseRentDO sourceHouseId(String sourceHouseId) {
    this.sourceHouseId = sourceHouseId;
    return this;
  }

   /**
   * Get sourceHouseId
   * @return sourceHouseId
  **/
  @ApiModelProperty(value = "")
  public String getSourceHouseId() {
    return sourceHouseId;
  }

  public void setSourceHouseId(String sourceHouseId) {
    this.sourceHouseId = sourceHouseId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiDropHouseRentDO apiDropHouseRentDO = (ApiDropHouseRentDO) o;
    return Objects.equals(this.city, apiDropHouseRentDO.city) &&
        Objects.equals(this.cityId, apiDropHouseRentDO.cityId) &&
        Objects.equals(this.company, apiDropHouseRentDO.company) &&
        Objects.equals(this.sourceHouseId, apiDropHouseRentDO.sourceHouseId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(city, cityId, company, sourceHouseId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiDropHouseRentDO {\n");
    
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    cityId: ").append(toIndentedString(cityId)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    sourceHouseId: ").append(toIndentedString(sourceHouseId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

