/*
 * Spring Boot使用 Swagger2 构建RestFul API
 * 接口文档
 *
 * OpenAPI spec version: v1
 * Contact: 123456@dongfangdi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bidewu.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ApiHouseRentDO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-26T06:55:57.895Z")
public class ApiHouseRentDO {
  @SerializedName("address")
  private String address = null;

  @SerializedName("agentId")
  private String agentId = null;

  @SerializedName("agentInfoCard")
  private String agentInfoCard = null;

  @SerializedName("agentList")
  private List<ApiHouseAgentDO> agentList = null;

  @SerializedName("agentName")
  private String agentName = null;

  @SerializedName("agentPic")
  private String agentPic = null;

  @SerializedName("agentTel")
  private String agentTel = null;

  @SerializedName("apartmentId")
  private Integer apartmentId = null;

  @SerializedName("apartmentIntroduce")
  private String apartmentIntroduce = null;

  @SerializedName("apartmentLogo")
  private String apartmentLogo = null;

  @SerializedName("apartmentName")
  private String apartmentName = null;

  @SerializedName("area")
  private BigDecimal area = null;

  @SerializedName("balcony")
  private Integer balcony = null;

  @SerializedName("category")
  private Integer category = null;

  @SerializedName("circle")
  private String circle = null;

  @SerializedName("city")
  private String city = null;

  @SerializedName("cityId")
  private Integer cityId = null;

  @SerializedName("company")
  private String company = null;

  @SerializedName("creatorId")
  private String creatorId = null;

  @SerializedName("displayTel")
  private String displayTel = null;

  @SerializedName("district")
  private String district = null;

  @SerializedName("fitment")
  private Integer fitment = null;

  @SerializedName("floor")
  private Integer floor = null;

  @SerializedName("floorLevel")
  private String floorLevel = null;

  @SerializedName("forward")
  private Integer forward = null;

  @SerializedName("hall")
  private Integer hall = null;

  @SerializedName("houseDesc")
  private String houseDesc = null;

  @SerializedName("houseTitle")
  private String houseTitle = null;

  @SerializedName("isDel")
  private Integer isDel = null;

  @SerializedName("kitchen")
  private Integer kitchen = null;

  @SerializedName("layoutPic")
  private List<String> layoutPic = null;

  @SerializedName("logoPic")
  private String logoPic = null;

  @SerializedName("lookHouseTime")
  private Integer lookHouseTime = null;

  @SerializedName("loupanId")
  private String loupanId = null;

  @SerializedName("loupanName")
  private String loupanName = null;

  @SerializedName("ofCompany")
  private String ofCompany = null;

  @SerializedName("outPic")
  private List<String> outPic = null;

  @SerializedName("payMode")
  private Integer payMode = null;

  @SerializedName("rentPrice")
  private BigDecimal rentPrice = null;

  @SerializedName("rentTags")
  private List<Integer> rentTags = null;

  @SerializedName("rentType")
  private Integer rentType = null;

  @SerializedName("room")
  private Integer room = null;

  @SerializedName("roomPic")
  private List<String> roomPic = null;

  @SerializedName("round")
  private String round = null;

  @SerializedName("source")
  private Integer source = null;

  @SerializedName("sourceHouseId")
  private String sourceHouseId = null;

  @SerializedName("status")
  private Integer status = null;

  @SerializedName("supportingFacilities")
  private List<String> supportingFacilities = null;

  @SerializedName("toilet")
  private Integer toilet = null;

  @SerializedName("totalFloor")
  private Integer totalFloor = null;

  @SerializedName("traffic")
  private String traffic = null;

  @SerializedName("updaterId")
  private String updaterId = null;

  public ApiHouseRentDO address(String address) {
    this.address = address;
    return this;
  }

  /**
   * Get address
   * @return address
   **/
  @ApiModelProperty(value = "")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public ApiHouseRentDO agentId(String agentId) {
    this.agentId = agentId;
    return this;
  }

  /**
   * Get agentId
   * @return agentId
   **/
  @ApiModelProperty(value = "")
  public String getAgentId() {
    return agentId;
  }

  public void setAgentId(String agentId) {
    this.agentId = agentId;
  }

  public ApiHouseRentDO agentInfoCard(String agentInfoCard) {
    this.agentInfoCard = agentInfoCard;
    return this;
  }

  /**
   * Get agentInfoCard
   * @return agentInfoCard
   **/
  @ApiModelProperty(value = "")
  public String getAgentInfoCard() {
    return agentInfoCard;
  }

  public void setAgentInfoCard(String agentInfoCard) {
    this.agentInfoCard = agentInfoCard;
  }

  public ApiHouseRentDO agentList(List<ApiHouseAgentDO> agentList) {
    this.agentList = agentList;
    return this;
  }

  public ApiHouseRentDO addAgentListItem(ApiHouseAgentDO agentListItem) {
    if (this.agentList == null) {
      this.agentList = new ArrayList<ApiHouseAgentDO>();
    }
    this.agentList.add(agentListItem);
    return this;
  }

  /**
   * Get agentList
   * @return agentList
   **/
  @ApiModelProperty(value = "")
  public List<ApiHouseAgentDO> getAgentList() {
    return agentList;
  }

  public void setAgentList(List<ApiHouseAgentDO> agentList) {
    this.agentList = agentList;
  }

  public ApiHouseRentDO agentName(String agentName) {
    this.agentName = agentName;
    return this;
  }

  /**
   * Get agentName
   * @return agentName
   **/
  @ApiModelProperty(value = "")
  public String getAgentName() {
    return agentName;
  }

  public void setAgentName(String agentName) {
    this.agentName = agentName;
  }

  public ApiHouseRentDO agentPic(String agentPic) {
    this.agentPic = agentPic;
    return this;
  }

  /**
   * Get agentPic
   * @return agentPic
   **/
  @ApiModelProperty(value = "")
  public String getAgentPic() {
    return agentPic;
  }

  public void setAgentPic(String agentPic) {
    this.agentPic = agentPic;
  }

  public ApiHouseRentDO agentTel(String agentTel) {
    this.agentTel = agentTel;
    return this;
  }

  /**
   * Get agentTel
   * @return agentTel
   **/
  @ApiModelProperty(value = "")
  public String getAgentTel() {
    return agentTel;
  }

  public void setAgentTel(String agentTel) {
    this.agentTel = agentTel;
  }

  public ApiHouseRentDO apartmentId(Integer apartmentId) {
    this.apartmentId = apartmentId;
    return this;
  }

  /**
   * Get apartmentId
   * @return apartmentId
   **/
  @ApiModelProperty(value = "")
  public Integer getApartmentId() {
    return apartmentId;
  }

  public void setApartmentId(Integer apartmentId) {
    this.apartmentId = apartmentId;
  }

  public ApiHouseRentDO apartmentIntroduce(String apartmentIntroduce) {
    this.apartmentIntroduce = apartmentIntroduce;
    return this;
  }

  /**
   * Get apartmentIntroduce
   * @return apartmentIntroduce
   **/
  @ApiModelProperty(value = "")
  public String getApartmentIntroduce() {
    return apartmentIntroduce;
  }

  public void setApartmentIntroduce(String apartmentIntroduce) {
    this.apartmentIntroduce = apartmentIntroduce;
  }

  public ApiHouseRentDO apartmentLogo(String apartmentLogo) {
    this.apartmentLogo = apartmentLogo;
    return this;
  }

  /**
   * Get apartmentLogo
   * @return apartmentLogo
   **/
  @ApiModelProperty(value = "")
  public String getApartmentLogo() {
    return apartmentLogo;
  }

  public void setApartmentLogo(String apartmentLogo) {
    this.apartmentLogo = apartmentLogo;
  }

  public ApiHouseRentDO apartmentName(String apartmentName) {
    this.apartmentName = apartmentName;
    return this;
  }

  /**
   * Get apartmentName
   * @return apartmentName
   **/
  @ApiModelProperty(value = "")
  public String getApartmentName() {
    return apartmentName;
  }

  public void setApartmentName(String apartmentName) {
    this.apartmentName = apartmentName;
  }

  public ApiHouseRentDO area(BigDecimal area) {
    this.area = area;
    return this;
  }

  /**
   * Get area
   * @return area
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getArea() {
    return area;
  }

  public void setArea(BigDecimal area) {
    this.area = area;
  }

  public ApiHouseRentDO balcony(Integer balcony) {
    this.balcony = balcony;
    return this;
  }

  /**
   * Get balcony
   * @return balcony
   **/
  @ApiModelProperty(value = "")
  public Integer getBalcony() {
    return balcony;
  }

  public void setBalcony(Integer balcony) {
    this.balcony = balcony;
  }

  public ApiHouseRentDO category(Integer category) {
    this.category = category;
    return this;
  }

  /**
   * Get category
   * @return category
   **/
  @ApiModelProperty(value = "")
  public Integer getCategory() {
    return category;
  }

  public void setCategory(Integer category) {
    this.category = category;
  }

  public ApiHouseRentDO circle(String circle) {
    this.circle = circle;
    return this;
  }

  /**
   * Get circle
   * @return circle
   **/
  @ApiModelProperty(value = "")
  public String getCircle() {
    return circle;
  }

  public void setCircle(String circle) {
    this.circle = circle;
  }

  public ApiHouseRentDO city(String city) {
    this.city = city;
    return this;
  }

  /**
   * Get city
   * @return city
   **/
  @ApiModelProperty(value = "")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public ApiHouseRentDO cityId(Integer cityId) {
    this.cityId = cityId;
    return this;
  }

  /**
   * Get cityId
   * @return cityId
   **/
  @ApiModelProperty(value = "")
  public Integer getCityId() {
    return cityId;
  }

  public void setCityId(Integer cityId) {
    this.cityId = cityId;
  }

  public ApiHouseRentDO company(String company) {
    this.company = company;
    return this;
  }

  /**
   * Get company
   * @return company
   **/
  @ApiModelProperty(value = "")
  public String getCompany() {
    return company;
  }

  public void setCompany(String company) {
    this.company = company;
  }

  public ApiHouseRentDO creatorId(String creatorId) {
    this.creatorId = creatorId;
    return this;
  }

  /**
   * Get creatorId
   * @return creatorId
   **/
  @ApiModelProperty(value = "")
  public String getCreatorId() {
    return creatorId;
  }

  public void setCreatorId(String creatorId) {
    this.creatorId = creatorId;
  }

  public ApiHouseRentDO displayTel(String displayTel) {
    this.displayTel = displayTel;
    return this;
  }

  /**
   * Get displayTel
   * @return displayTel
   **/
  @ApiModelProperty(value = "")
  public String getDisplayTel() {
    return displayTel;
  }

  public void setDisplayTel(String displayTel) {
    this.displayTel = displayTel;
  }

  public ApiHouseRentDO district(String district) {
    this.district = district;
    return this;
  }

  /**
   * Get district
   * @return district
   **/
  @ApiModelProperty(value = "")
  public String getDistrict() {
    return district;
  }

  public void setDistrict(String district) {
    this.district = district;
  }

  public ApiHouseRentDO fitment(Integer fitment) {
    this.fitment = fitment;
    return this;
  }

  /**
   * Get fitment
   * @return fitment
   **/
  @ApiModelProperty(value = "")
  public Integer getFitment() {
    return fitment;
  }

  public void setFitment(Integer fitment) {
    this.fitment = fitment;
  }

  public ApiHouseRentDO floor(Integer floor) {
    this.floor = floor;
    return this;
  }

  /**
   * Get floor
   * @return floor
   **/
  @ApiModelProperty(value = "")
  public Integer getFloor() {
    return floor;
  }

  public void setFloor(Integer floor) {
    this.floor = floor;
  }

  public ApiHouseRentDO floorLevel(String floorLevel) {
    this.floorLevel = floorLevel;
    return this;
  }

  /**
   * Get floorLevel
   * @return floorLevel
   **/
  @ApiModelProperty(value = "")
  public String getFloorLevel() {
    return floorLevel;
  }

  public void setFloorLevel(String floorLevel) {
    this.floorLevel = floorLevel;
  }

  public ApiHouseRentDO forward(Integer forward) {
    this.forward = forward;
    return this;
  }

  /**
   * Get forward
   * @return forward
   **/
  @ApiModelProperty(value = "")
  public Integer getForward() {
    return forward;
  }

  public void setForward(Integer forward) {
    this.forward = forward;
  }

  public ApiHouseRentDO hall(Integer hall) {
    this.hall = hall;
    return this;
  }

  /**
   * Get hall
   * @return hall
   **/
  @ApiModelProperty(value = "")
  public Integer getHall() {
    return hall;
  }

  public void setHall(Integer hall) {
    this.hall = hall;
  }

  public ApiHouseRentDO houseDesc(String houseDesc) {
    this.houseDesc = houseDesc;
    return this;
  }

  /**
   * Get houseDesc
   * @return houseDesc
   **/
  @ApiModelProperty(value = "")
  public String getHouseDesc() {
    return houseDesc;
  }

  public void setHouseDesc(String houseDesc) {
    this.houseDesc = houseDesc;
  }

  public ApiHouseRentDO houseTitle(String houseTitle) {
    this.houseTitle = houseTitle;
    return this;
  }

  /**
   * Get houseTitle
   * @return houseTitle
   **/
  @ApiModelProperty(value = "")
  public String getHouseTitle() {
    return houseTitle;
  }

  public void setHouseTitle(String houseTitle) {
    this.houseTitle = houseTitle;
  }

  public ApiHouseRentDO isDel(Integer isDel) {
    this.isDel = isDel;
    return this;
  }

  /**
   * Get isDel
   * @return isDel
   **/
  @ApiModelProperty(value = "")
  public Integer getIsDel() {
    return isDel;
  }

  public void setIsDel(Integer isDel) {
    this.isDel = isDel;
  }

  public ApiHouseRentDO kitchen(Integer kitchen) {
    this.kitchen = kitchen;
    return this;
  }

  /**
   * Get kitchen
   * @return kitchen
   **/
  @ApiModelProperty(value = "")
  public Integer getKitchen() {
    return kitchen;
  }

  public void setKitchen(Integer kitchen) {
    this.kitchen = kitchen;
  }

  public ApiHouseRentDO layoutPic(List<String> layoutPic) {
    this.layoutPic = layoutPic;
    return this;
  }

  public ApiHouseRentDO addLayoutPicItem(String layoutPicItem) {
    if (this.layoutPic == null) {
      this.layoutPic = new ArrayList<String>();
    }
    this.layoutPic.add(layoutPicItem);
    return this;
  }

  /**
   * Get layoutPic
   * @return layoutPic
   **/
  @ApiModelProperty(value = "")
  public List<String> getLayoutPic() {
    return layoutPic;
  }

  public void setLayoutPic(List<String> layoutPic) {
    this.layoutPic = layoutPic;
  }

  public ApiHouseRentDO logoPic(String logoPic) {
    this.logoPic = logoPic;
    return this;
  }

  /**
   * Get logoPic
   * @return logoPic
   **/
  @ApiModelProperty(value = "")
  public String getLogoPic() {
    return logoPic;
  }

  public void setLogoPic(String logoPic) {
    this.logoPic = logoPic;
  }

  public ApiHouseRentDO lookHouseTime(Integer lookHouseTime) {
    this.lookHouseTime = lookHouseTime;
    return this;
  }

  /**
   * Get lookHouseTime
   * @return lookHouseTime
   **/
  @ApiModelProperty(value = "")
  public Integer getLookHouseTime() {
    return lookHouseTime;
  }

  public void setLookHouseTime(Integer lookHouseTime) {
    this.lookHouseTime = lookHouseTime;
  }

  public ApiHouseRentDO loupanId(String loupanId) {
    this.loupanId = loupanId;
    return this;
  }

  /**
   * Get loupanId
   * @return loupanId
   **/
  @ApiModelProperty(value = "")
  public String getLoupanId() {
    return loupanId;
  }

  public void setLoupanId(String loupanId) {
    this.loupanId = loupanId;
  }

  public ApiHouseRentDO loupanName(String loupanName) {
    this.loupanName = loupanName;
    return this;
  }

  /**
   * Get loupanName
   * @return loupanName
   **/
  @ApiModelProperty(value = "")
  public String getLoupanName() {
    return loupanName;
  }

  public void setLoupanName(String loupanName) {
    this.loupanName = loupanName;
  }

  public ApiHouseRentDO ofCompany(String ofCompany) {
    this.ofCompany = ofCompany;
    return this;
  }

  /**
   * Get ofCompany
   * @return ofCompany
   **/
  @ApiModelProperty(value = "")
  public String getOfCompany() {
    return ofCompany;
  }

  public void setOfCompany(String ofCompany) {
    this.ofCompany = ofCompany;
  }

  public ApiHouseRentDO outPic(List<String> outPic) {
    this.outPic = outPic;
    return this;
  }

  public ApiHouseRentDO addOutPicItem(String outPicItem) {
    if (this.outPic == null) {
      this.outPic = new ArrayList<String>();
    }
    this.outPic.add(outPicItem);
    return this;
  }

  /**
   * Get outPic
   * @return outPic
   **/
  @ApiModelProperty(value = "")
  public List<String> getOutPic() {
    return outPic;
  }

  public void setOutPic(List<String> outPic) {
    this.outPic = outPic;
  }

  public ApiHouseRentDO payMode(Integer payMode) {
    this.payMode = payMode;
    return this;
  }

  /**
   * Get payMode
   * @return payMode
   **/
  @ApiModelProperty(value = "")
  public Integer getPayMode() {
    return payMode;
  }

  public void setPayMode(Integer payMode) {
    this.payMode = payMode;
  }

  public ApiHouseRentDO rentPrice(BigDecimal rentPrice) {
    this.rentPrice = rentPrice;
    return this;
  }

  /**
   * Get rentPrice
   * @return rentPrice
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getRentPrice() {
    return rentPrice;
  }

  public void setRentPrice(BigDecimal rentPrice) {
    this.rentPrice = rentPrice;
  }

  public ApiHouseRentDO rentTags(List<Integer> rentTags) {
    this.rentTags = rentTags;
    return this;
  }

  public ApiHouseRentDO addRentTagsItem(Integer rentTagsItem) {
    if (this.rentTags == null) {
      this.rentTags = new ArrayList<Integer>();
    }
    this.rentTags.add(rentTagsItem);
    return this;
  }

  /**
   * Get rentTags
   * @return rentTags
   **/
  @ApiModelProperty(value = "")
  public List<Integer> getRentTags() {
    return rentTags;
  }

  public void setRentTags(List<Integer> rentTags) {
    this.rentTags = rentTags;
  }

  public ApiHouseRentDO rentType(Integer rentType) {
    this.rentType = rentType;
    return this;
  }

  /**
   * Get rentType
   * @return rentType
   **/
  @ApiModelProperty(value = "")
  public Integer getRentType() {
    return rentType;
  }

  public void setRentType(Integer rentType) {
    this.rentType = rentType;
  }

  public ApiHouseRentDO room(Integer room) {
    this.room = room;
    return this;
  }

  /**
   * Get room
   * @return room
   **/
  @ApiModelProperty(value = "")
  public Integer getRoom() {
    return room;
  }

  public void setRoom(Integer room) {
    this.room = room;
  }

  public ApiHouseRentDO roomPic(List<String> roomPic) {
    this.roomPic = roomPic;
    return this;
  }

  public ApiHouseRentDO addRoomPicItem(String roomPicItem) {
    if (this.roomPic == null) {
      this.roomPic = new ArrayList<String>();
    }
    this.roomPic.add(roomPicItem);
    return this;
  }

  /**
   * Get roomPic
   * @return roomPic
   **/
  @ApiModelProperty(value = "")
  public List<String> getRoomPic() {
    return roomPic;
  }

  public void setRoomPic(List<String> roomPic) {
    this.roomPic = roomPic;
  }

  public ApiHouseRentDO round(String round) {
    this.round = round;
    return this;
  }

  /**
   * Get round
   * @return round
   **/
  @ApiModelProperty(value = "")
  public String getRound() {
    return round;
  }

  public void setRound(String round) {
    this.round = round;
  }

  public ApiHouseRentDO source(Integer source) {
    this.source = source;
    return this;
  }

  /**
   * Get source
   * @return source
   **/
  @ApiModelProperty(value = "")
  public Integer getSource() {
    return source;
  }

  public void setSource(Integer source) {
    this.source = source;
  }

  public ApiHouseRentDO sourceHouseId(String sourceHouseId) {
    this.sourceHouseId = sourceHouseId;
    return this;
  }

  /**
   * Get sourceHouseId
   * @return sourceHouseId
   **/
  @ApiModelProperty(value = "")
  public String getSourceHouseId() {
    return sourceHouseId;
  }

  public void setSourceHouseId(String sourceHouseId) {
    this.sourceHouseId = sourceHouseId;
  }

  public ApiHouseRentDO status(Integer status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   **/
  @ApiModelProperty(value = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public ApiHouseRentDO supportingFacilities(List<String> supportingFacilities) {
    this.supportingFacilities = supportingFacilities;
    return this;
  }

  public ApiHouseRentDO addSupportingFacilitiesItem(String supportingFacilitiesItem) {
    if (this.supportingFacilities == null) {
      this.supportingFacilities = new ArrayList<String>();
    }
    this.supportingFacilities.add(supportingFacilitiesItem);
    return this;
  }

  /**
   * Get supportingFacilities
   * @return supportingFacilities
   **/
  @ApiModelProperty(value = "")
  public List<String> getSupportingFacilities() {
    return supportingFacilities;
  }

  public void setSupportingFacilities(List<String> supportingFacilities) {
    this.supportingFacilities = supportingFacilities;
  }

  public ApiHouseRentDO toilet(Integer toilet) {
    this.toilet = toilet;
    return this;
  }

  /**
   * Get toilet
   * @return toilet
   **/
  @ApiModelProperty(value = "")
  public Integer getToilet() {
    return toilet;
  }

  public void setToilet(Integer toilet) {
    this.toilet = toilet;
  }

  public ApiHouseRentDO totalFloor(Integer totalFloor) {
    this.totalFloor = totalFloor;
    return this;
  }

  /**
   * Get totalFloor
   * @return totalFloor
   **/
  @ApiModelProperty(value = "")
  public Integer getTotalFloor() {
    return totalFloor;
  }

  public void setTotalFloor(Integer totalFloor) {
    this.totalFloor = totalFloor;
  }

  public ApiHouseRentDO traffic(String traffic) {
    this.traffic = traffic;
    return this;
  }

  /**
   * Get traffic
   * @return traffic
   **/
  @ApiModelProperty(value = "")
  public String getTraffic() {
    return traffic;
  }

  public void setTraffic(String traffic) {
    this.traffic = traffic;
  }

  public ApiHouseRentDO updaterId(String updaterId) {
    this.updaterId = updaterId;
    return this;
  }

  /**
   * Get updaterId
   * @return updaterId
   **/
  @ApiModelProperty(value = "")
  public String getUpdaterId() {
    return updaterId;
  }

  public void setUpdaterId(String updaterId) {
    this.updaterId = updaterId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiHouseRentDO apiHouseRentDO = (ApiHouseRentDO) o;
    return Objects.equals(this.address, apiHouseRentDO.address) &&
            Objects.equals(this.agentId, apiHouseRentDO.agentId) &&
            Objects.equals(this.agentInfoCard, apiHouseRentDO.agentInfoCard) &&
            Objects.equals(this.agentList, apiHouseRentDO.agentList) &&
            Objects.equals(this.agentName, apiHouseRentDO.agentName) &&
            Objects.equals(this.agentPic, apiHouseRentDO.agentPic) &&
            Objects.equals(this.agentTel, apiHouseRentDO.agentTel) &&
            Objects.equals(this.apartmentId, apiHouseRentDO.apartmentId) &&
            Objects.equals(this.apartmentIntroduce, apiHouseRentDO.apartmentIntroduce) &&
            Objects.equals(this.apartmentLogo, apiHouseRentDO.apartmentLogo) &&
            Objects.equals(this.apartmentName, apiHouseRentDO.apartmentName) &&
            Objects.equals(this.area, apiHouseRentDO.area) &&
            Objects.equals(this.balcony, apiHouseRentDO.balcony) &&
            Objects.equals(this.category, apiHouseRentDO.category) &&
            Objects.equals(this.circle, apiHouseRentDO.circle) &&
            Objects.equals(this.city, apiHouseRentDO.city) &&
            Objects.equals(this.cityId, apiHouseRentDO.cityId) &&
            Objects.equals(this.company, apiHouseRentDO.company) &&
            Objects.equals(this.creatorId, apiHouseRentDO.creatorId) &&
            Objects.equals(this.displayTel, apiHouseRentDO.displayTel) &&
            Objects.equals(this.district, apiHouseRentDO.district) &&
            Objects.equals(this.fitment, apiHouseRentDO.fitment) &&
            Objects.equals(this.floor, apiHouseRentDO.floor) &&
            Objects.equals(this.floorLevel, apiHouseRentDO.floorLevel) &&
            Objects.equals(this.forward, apiHouseRentDO.forward) &&
            Objects.equals(this.hall, apiHouseRentDO.hall) &&
            Objects.equals(this.houseDesc, apiHouseRentDO.houseDesc) &&
            Objects.equals(this.houseTitle, apiHouseRentDO.houseTitle) &&
            Objects.equals(this.isDel, apiHouseRentDO.isDel) &&
            Objects.equals(this.kitchen, apiHouseRentDO.kitchen) &&
            Objects.equals(this.layoutPic, apiHouseRentDO.layoutPic) &&
            Objects.equals(this.logoPic, apiHouseRentDO.logoPic) &&
            Objects.equals(this.lookHouseTime, apiHouseRentDO.lookHouseTime) &&
            Objects.equals(this.loupanId, apiHouseRentDO.loupanId) &&
            Objects.equals(this.loupanName, apiHouseRentDO.loupanName) &&
            Objects.equals(this.ofCompany, apiHouseRentDO.ofCompany) &&
            Objects.equals(this.outPic, apiHouseRentDO.outPic) &&
            Objects.equals(this.payMode, apiHouseRentDO.payMode) &&
            Objects.equals(this.rentPrice, apiHouseRentDO.rentPrice) &&
            Objects.equals(this.rentTags, apiHouseRentDO.rentTags) &&
            Objects.equals(this.rentType, apiHouseRentDO.rentType) &&
            Objects.equals(this.room, apiHouseRentDO.room) &&
            Objects.equals(this.roomPic, apiHouseRentDO.roomPic) &&
            Objects.equals(this.round, apiHouseRentDO.round) &&
            Objects.equals(this.source, apiHouseRentDO.source) &&
            Objects.equals(this.sourceHouseId, apiHouseRentDO.sourceHouseId) &&
            Objects.equals(this.status, apiHouseRentDO.status) &&
            Objects.equals(this.supportingFacilities, apiHouseRentDO.supportingFacilities) &&
            Objects.equals(this.toilet, apiHouseRentDO.toilet) &&
            Objects.equals(this.totalFloor, apiHouseRentDO.totalFloor) &&
            Objects.equals(this.traffic, apiHouseRentDO.traffic) &&
            Objects.equals(this.updaterId, apiHouseRentDO.updaterId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, agentId, agentInfoCard, agentList, agentName, agentPic, agentTel, apartmentId, apartmentIntroduce, apartmentLogo, apartmentName, area, balcony, category, circle, city, cityId, company, creatorId, displayTel, district, fitment, floor, floorLevel, forward, hall, houseDesc, houseTitle, isDel, kitchen, layoutPic, logoPic, lookHouseTime, loupanId, loupanName, ofCompany, outPic, payMode, rentPrice, rentTags, rentType, room, roomPic, round, source, sourceHouseId, status, supportingFacilities, toilet, totalFloor, traffic, updaterId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiHouseRentDO {\n");

    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    agentId: ").append(toIndentedString(agentId)).append("\n");
    sb.append("    agentInfoCard: ").append(toIndentedString(agentInfoCard)).append("\n");
    sb.append("    agentList: ").append(toIndentedString(agentList)).append("\n");
    sb.append("    agentName: ").append(toIndentedString(agentName)).append("\n");
    sb.append("    agentPic: ").append(toIndentedString(agentPic)).append("\n");
    sb.append("    agentTel: ").append(toIndentedString(agentTel)).append("\n");
    sb.append("    apartmentId: ").append(toIndentedString(apartmentId)).append("\n");
    sb.append("    apartmentIntroduce: ").append(toIndentedString(apartmentIntroduce)).append("\n");
    sb.append("    apartmentLogo: ").append(toIndentedString(apartmentLogo)).append("\n");
    sb.append("    apartmentName: ").append(toIndentedString(apartmentName)).append("\n");
    sb.append("    area: ").append(toIndentedString(area)).append("\n");
    sb.append("    balcony: ").append(toIndentedString(balcony)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    circle: ").append(toIndentedString(circle)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    cityId: ").append(toIndentedString(cityId)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    creatorId: ").append(toIndentedString(creatorId)).append("\n");
    sb.append("    displayTel: ").append(toIndentedString(displayTel)).append("\n");
    sb.append("    district: ").append(toIndentedString(district)).append("\n");
    sb.append("    fitment: ").append(toIndentedString(fitment)).append("\n");
    sb.append("    floor: ").append(toIndentedString(floor)).append("\n");
    sb.append("    floorLevel: ").append(toIndentedString(floorLevel)).append("\n");
    sb.append("    forward: ").append(toIndentedString(forward)).append("\n");
    sb.append("    hall: ").append(toIndentedString(hall)).append("\n");
    sb.append("    houseDesc: ").append(toIndentedString(houseDesc)).append("\n");
    sb.append("    houseTitle: ").append(toIndentedString(houseTitle)).append("\n");
    sb.append("    isDel: ").append(toIndentedString(isDel)).append("\n");
    sb.append("    kitchen: ").append(toIndentedString(kitchen)).append("\n");
    sb.append("    layoutPic: ").append(toIndentedString(layoutPic)).append("\n");
    sb.append("    logoPic: ").append(toIndentedString(logoPic)).append("\n");
    sb.append("    lookHouseTime: ").append(toIndentedString(lookHouseTime)).append("\n");
    sb.append("    loupanId: ").append(toIndentedString(loupanId)).append("\n");
    sb.append("    loupanName: ").append(toIndentedString(loupanName)).append("\n");
    sb.append("    ofCompany: ").append(toIndentedString(ofCompany)).append("\n");
    sb.append("    outPic: ").append(toIndentedString(outPic)).append("\n");
    sb.append("    payMode: ").append(toIndentedString(payMode)).append("\n");
    sb.append("    rentPrice: ").append(toIndentedString(rentPrice)).append("\n");
    sb.append("    rentTags: ").append(toIndentedString(rentTags)).append("\n");
    sb.append("    rentType: ").append(toIndentedString(rentType)).append("\n");
    sb.append("    room: ").append(toIndentedString(room)).append("\n");
    sb.append("    roomPic: ").append(toIndentedString(roomPic)).append("\n");
    sb.append("    round: ").append(toIndentedString(round)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    sourceHouseId: ").append(toIndentedString(sourceHouseId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    supportingFacilities: ").append(toIndentedString(supportingFacilities)).append("\n");
    sb.append("    toilet: ").append(toIndentedString(toilet)).append("\n");
    sb.append("    totalFloor: ").append(toIndentedString(totalFloor)).append("\n");
    sb.append("    traffic: ").append(toIndentedString(traffic)).append("\n");
    sb.append("    updaterId: ").append(toIndentedString(updaterId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

