/*
 * Spring Boot使用 Swagger2 构建RestFul API
 * 接口文档
 *
 * OpenAPI spec version: v1
 * Contact: 123456@dongfangdi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bidewu.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ApiHouseResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-26T06:55:57.895Z")
public class ApiHouseResult {
  @SerializedName("apiHouseId")
  private String apiHouseId = null;

  @SerializedName("housePreviewUrl")
  private String housePreviewUrl = null;

  public ApiHouseResult apiHouseId(String apiHouseId) {
    this.apiHouseId = apiHouseId;
    return this;
  }

   /**
   * 头条房产房源Id
   * @return apiHouseId
  **/
  @ApiModelProperty(value = "头条房产房源Id")
  public String getApiHouseId() {
    return apiHouseId;
  }

  public void setApiHouseId(String apiHouseId) {
    this.apiHouseId = apiHouseId;
  }

  public ApiHouseResult housePreviewUrl(String housePreviewUrl) {
    this.housePreviewUrl = housePreviewUrl;
    return this;
  }

   /**
   * 头条房产房源预览Url
   * @return housePreviewUrl
  **/
  @ApiModelProperty(value = "头条房产房源预览Url")
  public String getHousePreviewUrl() {
    return housePreviewUrl;
  }

  public void setHousePreviewUrl(String housePreviewUrl) {
    this.housePreviewUrl = housePreviewUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiHouseResult apiHouseResult = (ApiHouseResult) o;
    return Objects.equals(this.apiHouseId, apiHouseResult.apiHouseId) &&
        Objects.equals(this.housePreviewUrl, apiHouseResult.housePreviewUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiHouseId, housePreviewUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiHouseResult {\n");
    
    sb.append("    apiHouseId: ").append(toIndentedString(apiHouseId)).append("\n");
    sb.append("    housePreviewUrl: ").append(toIndentedString(housePreviewUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

