/*
 * Spring Boot使用 Swagger2 构建RestFul API
 * 接口文档
 *
 * OpenAPI spec version: v1
 * Contact: 123456@dongfangdi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bidewu.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;

/**
 * HouseImportDO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-26T06:55:57.895Z")
public class HouseImportDO {
  @SerializedName("accessory")
  private String accessory = null;

  @SerializedName("address")
  private String address = null;

  @SerializedName("agentId")
  private String agentId = null;

  @SerializedName("agentInfoCard")
  private String agentInfoCard = null;

  @SerializedName("agentName")
  private String agentName = null;

  @SerializedName("agentPic")
  private String agentPic = null;

  @SerializedName("agentTel")
  private String agentTel = null;

  @SerializedName("balcony")
  private Integer balcony = null;

  @SerializedName("buildArea")
  private Double buildArea = null;

  @SerializedName("buildCategory")
  private Integer buildCategory = null;

  @SerializedName("buildForm")
  private Integer buildForm = null;

  @SerializedName("circle")
  private String circle = null;

  @SerializedName("city")
  private String city = null;

  @SerializedName("cityId")
  private Integer cityId = null;

  @SerializedName("creatorId")
  private Integer creatorId = null;

  @SerializedName("displayTel")
  private String displayTel = null;

  @SerializedName("district")
  private String district = null;

  @SerializedName("fangyuanId")
  private String fangyuanId = null;

  @SerializedName("fitment")
  private Integer fitment = null;

  @SerializedName("floor")
  private String floor = null;

  @SerializedName("floorNo")
  private Integer floorNo = null;

  @SerializedName("forward")
  private Integer forward = null;

  @SerializedName("hall")
  private Integer hall = null;

  @SerializedName("houseDesc")
  private String houseDesc = null;

  @SerializedName("houseTitle")
  private String houseTitle = null;

  @SerializedName("houseType")
  private Integer houseType = null;

  @SerializedName("kitchen")
  private Integer kitchen = null;

  @SerializedName("layoutPic")
  private List<String> layoutPic = null;

  @SerializedName("logoPic")
  private String logoPic = null;

  @SerializedName("lookTime")
  private Integer lookTime = null;

  @SerializedName("loupanId")
  private String loupanId = null;

  @SerializedName("ofCompany")
  private String ofCompany = null;

  @SerializedName("ofCompanyEn")
  private String ofCompanyEn = null;

  @SerializedName("outPic")
  private List<String> outPic = null;

  @SerializedName("price")
  private Double price = null;

  @SerializedName("priceUnit")
  private String priceUnit = null;

  @SerializedName("projName")
  private String projName = null;

  @SerializedName("propertyRight")
  private Integer propertyRight = null;

  @SerializedName("room")
  private Integer room = null;

  @SerializedName("roomPic")
  private List<String> roomPic = null;

  @SerializedName("round")
  private String round = null;

  @SerializedName("tagStrArray")
  private List<String> tagStrArray = null;

  @SerializedName("tags")
  private List<Integer> tags = null;

  @SerializedName("toilet")
  private Integer toilet = null;

  @SerializedName("totalFloor")
  private Integer totalFloor = null;

  @SerializedName("traffic")
  private String traffic = null;

  @SerializedName("updateTime")
  private Date updateTime = null;

  @SerializedName("updaterId")
  private Integer updaterId = null;

  @SerializedName("year")
  private String year = null;

  public HouseImportDO accessory(String accessory) {
    this.accessory = accessory;
    return this;
  }

  /**
   * Get accessory
   * @return accessory
   **/
  @ApiModelProperty(value = "")
  public String getAccessory() {
    return accessory;
  }

  public void setAccessory(String accessory) {
    this.accessory = accessory;
  }

  public HouseImportDO address(String address) {
    this.address = address;
    return this;
  }

  /**
   * Get address
   * @return address
   **/
  @ApiModelProperty(value = "")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public HouseImportDO agentId(String agentId) {
    this.agentId = agentId;
    return this;
  }

  /**
   * Get agentId
   * @return agentId
   **/
  @ApiModelProperty(value = "")
  public String getAgentId() {
    return agentId;
  }

  public void setAgentId(String agentId) {
    this.agentId = agentId;
  }

  public HouseImportDO agentInfoCard(String agentInfoCard) {
    this.agentInfoCard = agentInfoCard;
    return this;
  }

  /**
   * Get agentInfoCard
   * @return agentInfoCard
   **/
  @ApiModelProperty(value = "")
  public String getAgentInfoCard() {
    return agentInfoCard;
  }

  public void setAgentInfoCard(String agentInfoCard) {
    this.agentInfoCard = agentInfoCard;
  }

  public HouseImportDO agentName(String agentName) {
    this.agentName = agentName;
    return this;
  }

  /**
   * Get agentName
   * @return agentName
   **/
  @ApiModelProperty(value = "")
  public String getAgentName() {
    return agentName;
  }

  public void setAgentName(String agentName) {
    this.agentName = agentName;
  }

  public HouseImportDO agentPic(String agentPic) {
    this.agentPic = agentPic;
    return this;
  }

  /**
   * Get agentPic
   * @return agentPic
   **/
  @ApiModelProperty(value = "")
  public String getAgentPic() {
    return agentPic;
  }

  public void setAgentPic(String agentPic) {
    this.agentPic = agentPic;
  }

  public HouseImportDO agentTel(String agentTel) {
    this.agentTel = agentTel;
    return this;
  }

  /**
   * Get agentTel
   * @return agentTel
   **/
  @ApiModelProperty(value = "")
  public String getAgentTel() {
    return agentTel;
  }

  public void setAgentTel(String agentTel) {
    this.agentTel = agentTel;
  }

  public HouseImportDO balcony(Integer balcony) {
    this.balcony = balcony;
    return this;
  }

  /**
   * Get balcony
   * @return balcony
   **/
  @ApiModelProperty(value = "")
  public Integer getBalcony() {
    return balcony;
  }

  public void setBalcony(Integer balcony) {
    this.balcony = balcony;
  }

  public HouseImportDO buildArea(Double buildArea) {
    this.buildArea = buildArea;
    return this;
  }

  /**
   * Get buildArea
   * @return buildArea
   **/
  @ApiModelProperty(value = "")
  public Double getBuildArea() {
    return buildArea;
  }

  public void setBuildArea(Double buildArea) {
    this.buildArea = buildArea;
  }

  public HouseImportDO buildCategory(Integer buildCategory) {
    this.buildCategory = buildCategory;
    return this;
  }

  /**
   * Get buildCategory
   * @return buildCategory
   **/
  @ApiModelProperty(value = "")
  public Integer getBuildCategory() {
    return buildCategory;
  }

  public void setBuildCategory(Integer buildCategory) {
    this.buildCategory = buildCategory;
  }

  public HouseImportDO buildForm(Integer buildForm) {
    this.buildForm = buildForm;
    return this;
  }

  /**
   * Get buildForm
   * @return buildForm
   **/
  @ApiModelProperty(value = "")
  public Integer getBuildForm() {
    return buildForm;
  }

  public void setBuildForm(Integer buildForm) {
    this.buildForm = buildForm;
  }

  public HouseImportDO circle(String circle) {
    this.circle = circle;
    return this;
  }

  /**
   * Get circle
   * @return circle
   **/
  @ApiModelProperty(value = "")
  public String getCircle() {
    return circle;
  }

  public void setCircle(String circle) {
    this.circle = circle;
  }

  public HouseImportDO city(String city) {
    this.city = city;
    return this;
  }

  /**
   * Get city
   * @return city
   **/
  @ApiModelProperty(value = "")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public HouseImportDO cityId(Integer cityId) {
    this.cityId = cityId;
    return this;
  }

  /**
   * Get cityId
   * @return cityId
   **/
  @ApiModelProperty(value = "")
  public Integer getCityId() {
    return cityId;
  }

  public void setCityId(Integer cityId) {
    this.cityId = cityId;
  }

  public HouseImportDO creatorId(Integer creatorId) {
    this.creatorId = creatorId;
    return this;
  }

  /**
   * Get creatorId
   * @return creatorId
   **/
  @ApiModelProperty(value = "")
  public Integer getCreatorId() {
    return creatorId;
  }

  public void setCreatorId(Integer creatorId) {
    this.creatorId = creatorId;
  }

  public HouseImportDO displayTel(String displayTel) {
    this.displayTel = displayTel;
    return this;
  }

  /**
   * Get displayTel
   * @return displayTel
   **/
  @ApiModelProperty(value = "")
  public String getDisplayTel() {
    return displayTel;
  }

  public void setDisplayTel(String displayTel) {
    this.displayTel = displayTel;
  }

  public HouseImportDO district(String district) {
    this.district = district;
    return this;
  }

  /**
   * Get district
   * @return district
   **/
  @ApiModelProperty(value = "")
  public String getDistrict() {
    return district;
  }

  public void setDistrict(String district) {
    this.district = district;
  }

  public HouseImportDO fangyuanId(String fangyuanId) {
    this.fangyuanId = fangyuanId;
    return this;
  }

  /**
   * Get fangyuanId
   * @return fangyuanId
   **/
  @ApiModelProperty(value = "")
  public String getFangyuanId() {
    return fangyuanId;
  }

  public void setFangyuanId(String fangyuanId) {
    this.fangyuanId = fangyuanId;
  }

  public HouseImportDO fitment(Integer fitment) {
    this.fitment = fitment;
    return this;
  }

  /**
   * Get fitment
   * @return fitment
   **/
  @ApiModelProperty(value = "")
  public Integer getFitment() {
    return fitment;
  }

  public void setFitment(Integer fitment) {
    this.fitment = fitment;
  }

  public HouseImportDO floor(String floor) {
    this.floor = floor;
    return this;
  }

  /**
   * Get floor
   * @return floor
   **/
  @ApiModelProperty(value = "")
  public String getFloor() {
    return floor;
  }

  public void setFloor(String floor) {
    this.floor = floor;
  }

  public HouseImportDO floorNo(Integer floorNo) {
    this.floorNo = floorNo;
    return this;
  }

  /**
   * Get floorNo
   * @return floorNo
   **/
  @ApiModelProperty(value = "")
  public Integer getFloorNo() {
    return floorNo;
  }

  public void setFloorNo(Integer floorNo) {
    this.floorNo = floorNo;
  }

  public HouseImportDO forward(Integer forward) {
    this.forward = forward;
    return this;
  }

  /**
   * Get forward
   * @return forward
   **/
  @ApiModelProperty(value = "")
  public Integer getForward() {
    return forward;
  }

  public void setForward(Integer forward) {
    this.forward = forward;
  }

  public HouseImportDO hall(Integer hall) {
    this.hall = hall;
    return this;
  }

  /**
   * Get hall
   * @return hall
   **/
  @ApiModelProperty(value = "")
  public Integer getHall() {
    return hall;
  }

  public void setHall(Integer hall) {
    this.hall = hall;
  }

  public HouseImportDO houseDesc(String houseDesc) {
    this.houseDesc = houseDesc;
    return this;
  }

  /**
   * Get houseDesc
   * @return houseDesc
   **/
  @ApiModelProperty(value = "")
  public String getHouseDesc() {
    return houseDesc;
  }

  public void setHouseDesc(String houseDesc) {
    this.houseDesc = houseDesc;
  }

  public HouseImportDO houseTitle(String houseTitle) {
    this.houseTitle = houseTitle;
    return this;
  }

  /**
   * Get houseTitle
   * @return houseTitle
   **/
  @ApiModelProperty(value = "")
  public String getHouseTitle() {
    return houseTitle;
  }

  public void setHouseTitle(String houseTitle) {
    this.houseTitle = houseTitle;
  }

  public HouseImportDO houseType(Integer houseType) {
    this.houseType = houseType;
    return this;
  }

  /**
   * Get houseType
   * @return houseType
   **/
  @ApiModelProperty(value = "")
  public Integer getHouseType() {
    return houseType;
  }

  public void setHouseType(Integer houseType) {
    this.houseType = houseType;
  }

  public HouseImportDO kitchen(Integer kitchen) {
    this.kitchen = kitchen;
    return this;
  }

  /**
   * Get kitchen
   * @return kitchen
   **/
  @ApiModelProperty(value = "")
  public Integer getKitchen() {
    return kitchen;
  }

  public void setKitchen(Integer kitchen) {
    this.kitchen = kitchen;
  }

  public HouseImportDO layoutPic(List<String> layoutPic) {
    this.layoutPic = layoutPic;
    return this;
  }

  public HouseImportDO addLayoutPicItem(String layoutPicItem) {
    if (this.layoutPic == null) {
      this.layoutPic = new ArrayList<String>();
    }
    this.layoutPic.add(layoutPicItem);
    return this;
  }

  /**
   * Get layoutPic
   * @return layoutPic
   **/
  @ApiModelProperty(value = "")
  public List<String> getLayoutPic() {
    return layoutPic;
  }

  public void setLayoutPic(List<String> layoutPic) {
    this.layoutPic = layoutPic;
  }

  public HouseImportDO logoPic(String logoPic) {
    this.logoPic = logoPic;
    return this;
  }

  /**
   * Get logoPic
   * @return logoPic
   **/
  @ApiModelProperty(value = "")
  public String getLogoPic() {
    return logoPic;
  }

  public void setLogoPic(String logoPic) {
    this.logoPic = logoPic;
  }

  public HouseImportDO lookTime(Integer lookTime) {
    this.lookTime = lookTime;
    return this;
  }

  /**
   * Get lookTime
   * @return lookTime
   **/
  @ApiModelProperty(value = "")
  public Integer getLookTime() {
    return lookTime;
  }

  public void setLookTime(Integer lookTime) {
    this.lookTime = lookTime;
  }

  public HouseImportDO loupanId(String loupanId) {
    this.loupanId = loupanId;
    return this;
  }

  /**
   * Get loupanId
   * @return loupanId
   **/
  @ApiModelProperty(value = "")
  public String getLoupanId() {
    return loupanId;
  }

  public void setLoupanId(String loupanId) {
    this.loupanId = loupanId;
  }

  public HouseImportDO ofCompany(String ofCompany) {
    this.ofCompany = ofCompany;
    return this;
  }

  /**
   * Get ofCompany
   * @return ofCompany
   **/
  @ApiModelProperty(value = "")
  public String getOfCompany() {
    return ofCompany;
  }

  public void setOfCompany(String ofCompany) {
    this.ofCompany = ofCompany;
  }

  public HouseImportDO ofCompanyEn(String ofCompanyEn) {
    this.ofCompanyEn = ofCompanyEn;
    return this;
  }

  /**
   * Get ofCompanyEn
   * @return ofCompanyEn
   **/
  @ApiModelProperty(value = "")
  public String getOfCompanyEn() {
    return ofCompanyEn;
  }

  public void setOfCompanyEn(String ofCompanyEn) {
    this.ofCompanyEn = ofCompanyEn;
  }

  public HouseImportDO outPic(List<String> outPic) {
    this.outPic = outPic;
    return this;
  }

  public HouseImportDO addOutPicItem(String outPicItem) {
    if (this.outPic == null) {
      this.outPic = new ArrayList<String>();
    }
    this.outPic.add(outPicItem);
    return this;
  }

  /**
   * Get outPic
   * @return outPic
   **/
  @ApiModelProperty(value = "")
  public List<String> getOutPic() {
    return outPic;
  }

  public void setOutPic(List<String> outPic) {
    this.outPic = outPic;
  }

  public HouseImportDO price(Double price) {
    this.price = price;
    return this;
  }

  /**
   * Get price
   * @return price
   **/
  @ApiModelProperty(value = "")
  public Double getPrice() {
    return price;
  }

  public void setPrice(Double price) {
    this.price = price;
  }

  public HouseImportDO priceUnit(String priceUnit) {
    this.priceUnit = priceUnit;
    return this;
  }

  /**
   * Get priceUnit
   * @return priceUnit
   **/
  @ApiModelProperty(value = "")
  public String getPriceUnit() {
    return priceUnit;
  }

  public void setPriceUnit(String priceUnit) {
    this.priceUnit = priceUnit;
  }

  public HouseImportDO projName(String projName) {
    this.projName = projName;
    return this;
  }

  /**
   * Get projName
   * @return projName
   **/
  @ApiModelProperty(value = "")
  public String getProjName() {
    return projName;
  }

  public void setProjName(String projName) {
    this.projName = projName;
  }

  public HouseImportDO propertyRight(Integer propertyRight) {
    this.propertyRight = propertyRight;
    return this;
  }

  /**
   * Get propertyRight
   * @return propertyRight
   **/
  @ApiModelProperty(value = "")
  public Integer getPropertyRight() {
    return propertyRight;
  }

  public void setPropertyRight(Integer propertyRight) {
    this.propertyRight = propertyRight;
  }

  public HouseImportDO room(Integer room) {
    this.room = room;
    return this;
  }

  /**
   * Get room
   * @return room
   **/
  @ApiModelProperty(value = "")
  public Integer getRoom() {
    return room;
  }

  public void setRoom(Integer room) {
    this.room = room;
  }

  public HouseImportDO roomPic(List<String> roomPic) {
    this.roomPic = roomPic;
    return this;
  }

  public HouseImportDO addRoomPicItem(String roomPicItem) {
    if (this.roomPic == null) {
      this.roomPic = new ArrayList<String>();
    }
    this.roomPic.add(roomPicItem);
    return this;
  }

  /**
   * Get roomPic
   * @return roomPic
   **/
  @ApiModelProperty(value = "")
  public List<String> getRoomPic() {
    return roomPic;
  }

  public void setRoomPic(List<String> roomPic) {
    this.roomPic = roomPic;
  }

  public HouseImportDO round(String round) {
    this.round = round;
    return this;
  }

  /**
   * Get round
   * @return round
   **/
  @ApiModelProperty(value = "")
  public String getRound() {
    return round;
  }

  public void setRound(String round) {
    this.round = round;
  }

  public HouseImportDO tagStrArray(List<String> tagStrArray) {
    this.tagStrArray = tagStrArray;
    return this;
  }

  public HouseImportDO addTagStrArrayItem(String tagStrArrayItem) {
    if (this.tagStrArray == null) {
      this.tagStrArray = new ArrayList<String>();
    }
    this.tagStrArray.add(tagStrArrayItem);
    return this;
  }

  /**
   * Get tagStrArray
   * @return tagStrArray
   **/
  @ApiModelProperty(value = "")
  public List<String> getTagStrArray() {
    return tagStrArray;
  }

  public void setTagStrArray(List<String> tagStrArray) {
    this.tagStrArray = tagStrArray;
  }

  public HouseImportDO tags(List<Integer> tags) {
    this.tags = tags;
    return this;
  }

  public HouseImportDO addTagsItem(Integer tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<Integer>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   **/
  @ApiModelProperty(value = "")
  public List<Integer> getTags() {
    return tags;
  }

  public void setTags(List<Integer> tags) {
    this.tags = tags;
  }

  public HouseImportDO toilet(Integer toilet) {
    this.toilet = toilet;
    return this;
  }

  /**
   * Get toilet
   * @return toilet
   **/
  @ApiModelProperty(value = "")
  public Integer getToilet() {
    return toilet;
  }

  public void setToilet(Integer toilet) {
    this.toilet = toilet;
  }

  public HouseImportDO totalFloor(Integer totalFloor) {
    this.totalFloor = totalFloor;
    return this;
  }

  /**
   * Get totalFloor
   * @return totalFloor
   **/
  @ApiModelProperty(value = "")
  public Integer getTotalFloor() {
    return totalFloor;
  }

  public void setTotalFloor(Integer totalFloor) {
    this.totalFloor = totalFloor;
  }

  public HouseImportDO traffic(String traffic) {
    this.traffic = traffic;
    return this;
  }

  /**
   * Get traffic
   * @return traffic
   **/
  @ApiModelProperty(value = "")
  public String getTraffic() {
    return traffic;
  }

  public void setTraffic(String traffic) {
    this.traffic = traffic;
  }

  public HouseImportDO updateTime(Date updateTime) {
    this.updateTime = updateTime;
    return this;
  }

  /**
   * Get updateTime
   * @return updateTime
   **/
  @ApiModelProperty(value = "")
  public Date getUpdateTime() {
    return updateTime;
  }

  public void setUpdateTime(Date updateTime) {
    this.updateTime = updateTime;
  }

  public HouseImportDO updaterId(Integer updaterId) {
    this.updaterId = updaterId;
    return this;
  }

  /**
   * Get updaterId
   * @return updaterId
   **/
  @ApiModelProperty(value = "")
  public Integer getUpdaterId() {
    return updaterId;
  }

  public void setUpdaterId(Integer updaterId) {
    this.updaterId = updaterId;
  }

  public HouseImportDO year(String year) {
    this.year = year;
    return this;
  }

  /**
   * Get year
   * @return year
   **/
  @ApiModelProperty(value = "")
  public String getYear() {
    return year;
  }

  public void setYear(String year) {
    this.year = year;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HouseImportDO houseImportDO = (HouseImportDO) o;
    return Objects.equals(this.accessory, houseImportDO.accessory) &&
            Objects.equals(this.address, houseImportDO.address) &&
            Objects.equals(this.agentId, houseImportDO.agentId) &&
            Objects.equals(this.agentInfoCard, houseImportDO.agentInfoCard) &&
            Objects.equals(this.agentName, houseImportDO.agentName) &&
            Objects.equals(this.agentPic, houseImportDO.agentPic) &&
            Objects.equals(this.agentTel, houseImportDO.agentTel) &&
            Objects.equals(this.balcony, houseImportDO.balcony) &&
            Objects.equals(this.buildArea, houseImportDO.buildArea) &&
            Objects.equals(this.buildCategory, houseImportDO.buildCategory) &&
            Objects.equals(this.buildForm, houseImportDO.buildForm) &&
            Objects.equals(this.circle, houseImportDO.circle) &&
            Objects.equals(this.city, houseImportDO.city) &&
            Objects.equals(this.cityId, houseImportDO.cityId) &&
            Objects.equals(this.creatorId, houseImportDO.creatorId) &&
            Objects.equals(this.displayTel, houseImportDO.displayTel) &&
            Objects.equals(this.district, houseImportDO.district) &&
            Objects.equals(this.fangyuanId, houseImportDO.fangyuanId) &&
            Objects.equals(this.fitment, houseImportDO.fitment) &&
            Objects.equals(this.floor, houseImportDO.floor) &&
            Objects.equals(this.floorNo, houseImportDO.floorNo) &&
            Objects.equals(this.forward, houseImportDO.forward) &&
            Objects.equals(this.hall, houseImportDO.hall) &&
            Objects.equals(this.houseDesc, houseImportDO.houseDesc) &&
            Objects.equals(this.houseTitle, houseImportDO.houseTitle) &&
            Objects.equals(this.houseType, houseImportDO.houseType) &&
            Objects.equals(this.kitchen, houseImportDO.kitchen) &&
            Objects.equals(this.layoutPic, houseImportDO.layoutPic) &&
            Objects.equals(this.logoPic, houseImportDO.logoPic) &&
            Objects.equals(this.lookTime, houseImportDO.lookTime) &&
            Objects.equals(this.loupanId, houseImportDO.loupanId) &&
            Objects.equals(this.ofCompany, houseImportDO.ofCompany) &&
            Objects.equals(this.ofCompanyEn, houseImportDO.ofCompanyEn) &&
            Objects.equals(this.outPic, houseImportDO.outPic) &&
            Objects.equals(this.price, houseImportDO.price) &&
            Objects.equals(this.priceUnit, houseImportDO.priceUnit) &&
            Objects.equals(this.projName, houseImportDO.projName) &&
            Objects.equals(this.propertyRight, houseImportDO.propertyRight) &&
            Objects.equals(this.room, houseImportDO.room) &&
            Objects.equals(this.roomPic, houseImportDO.roomPic) &&
            Objects.equals(this.round, houseImportDO.round) &&
            Objects.equals(this.tagStrArray, houseImportDO.tagStrArray) &&
            Objects.equals(this.tags, houseImportDO.tags) &&
            Objects.equals(this.toilet, houseImportDO.toilet) &&
            Objects.equals(this.totalFloor, houseImportDO.totalFloor) &&
            Objects.equals(this.traffic, houseImportDO.traffic) &&
            Objects.equals(this.updateTime, houseImportDO.updateTime) &&
            Objects.equals(this.updaterId, houseImportDO.updaterId) &&
            Objects.equals(this.year, houseImportDO.year);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessory, address, agentId, agentInfoCard, agentName, agentPic, agentTel, balcony, buildArea, buildCategory, buildForm, circle, city, cityId, creatorId, displayTel, district, fangyuanId, fitment, floor, floorNo, forward, hall, houseDesc, houseTitle, houseType, kitchen, layoutPic, logoPic, lookTime, loupanId, ofCompany, ofCompanyEn, outPic, price, priceUnit, projName, propertyRight, room, roomPic, round, tagStrArray, tags, toilet, totalFloor, traffic, updateTime, updaterId, year);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HouseImportDO {\n");

    sb.append("    accessory: ").append(toIndentedString(accessory)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    agentId: ").append(toIndentedString(agentId)).append("\n");
    sb.append("    agentInfoCard: ").append(toIndentedString(agentInfoCard)).append("\n");
    sb.append("    agentName: ").append(toIndentedString(agentName)).append("\n");
    sb.append("    agentPic: ").append(toIndentedString(agentPic)).append("\n");
    sb.append("    agentTel: ").append(toIndentedString(agentTel)).append("\n");
    sb.append("    balcony: ").append(toIndentedString(balcony)).append("\n");
    sb.append("    buildArea: ").append(toIndentedString(buildArea)).append("\n");
    sb.append("    buildCategory: ").append(toIndentedString(buildCategory)).append("\n");
    sb.append("    buildForm: ").append(toIndentedString(buildForm)).append("\n");
    sb.append("    circle: ").append(toIndentedString(circle)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    cityId: ").append(toIndentedString(cityId)).append("\n");
    sb.append("    creatorId: ").append(toIndentedString(creatorId)).append("\n");
    sb.append("    displayTel: ").append(toIndentedString(displayTel)).append("\n");
    sb.append("    district: ").append(toIndentedString(district)).append("\n");
    sb.append("    fangyuanId: ").append(toIndentedString(fangyuanId)).append("\n");
    sb.append("    fitment: ").append(toIndentedString(fitment)).append("\n");
    sb.append("    floor: ").append(toIndentedString(floor)).append("\n");
    sb.append("    floorNo: ").append(toIndentedString(floorNo)).append("\n");
    sb.append("    forward: ").append(toIndentedString(forward)).append("\n");
    sb.append("    hall: ").append(toIndentedString(hall)).append("\n");
    sb.append("    houseDesc: ").append(toIndentedString(houseDesc)).append("\n");
    sb.append("    houseTitle: ").append(toIndentedString(houseTitle)).append("\n");
    sb.append("    houseType: ").append(toIndentedString(houseType)).append("\n");
    sb.append("    kitchen: ").append(toIndentedString(kitchen)).append("\n");
    sb.append("    layoutPic: ").append(toIndentedString(layoutPic)).append("\n");
    sb.append("    logoPic: ").append(toIndentedString(logoPic)).append("\n");
    sb.append("    lookTime: ").append(toIndentedString(lookTime)).append("\n");
    sb.append("    loupanId: ").append(toIndentedString(loupanId)).append("\n");
    sb.append("    ofCompany: ").append(toIndentedString(ofCompany)).append("\n");
    sb.append("    ofCompanyEn: ").append(toIndentedString(ofCompanyEn)).append("\n");
    sb.append("    outPic: ").append(toIndentedString(outPic)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    priceUnit: ").append(toIndentedString(priceUnit)).append("\n");
    sb.append("    projName: ").append(toIndentedString(projName)).append("\n");
    sb.append("    propertyRight: ").append(toIndentedString(propertyRight)).append("\n");
    sb.append("    room: ").append(toIndentedString(room)).append("\n");
    sb.append("    roomPic: ").append(toIndentedString(roomPic)).append("\n");
    sb.append("    round: ").append(toIndentedString(round)).append("\n");
    sb.append("    tagStrArray: ").append(toIndentedString(tagStrArray)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    toilet: ").append(toIndentedString(toilet)).append("\n");
    sb.append("    totalFloor: ").append(toIndentedString(totalFloor)).append("\n");
    sb.append("    traffic: ").append(toIndentedString(traffic)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("    updaterId: ").append(toIndentedString(updaterId)).append("\n");
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

