/*
 * Spring Boot使用 Swagger2 构建RestFul API
 * 接口文档
 *
 * OpenAPI spec version: v1
 * Contact: 123456@dongfangdi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bidewu.model;

import java.util.Objects;
import java.util.Arrays;
import com.bidewu.model.ApiHouseResult;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * HouseRentResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-26T06:55:57.895Z")
public class HouseRentResponse {
  @SerializedName("data")
  private List<ApiHouseResult> data = null;

  @SerializedName("totalNum")
  private Integer totalNum = null;

  public HouseRentResponse data(List<ApiHouseResult> data) {
    this.data = data;
    return this;
  }

  public HouseRentResponse addDataItem(ApiHouseResult dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<ApiHouseResult>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * 数据
   * @return data
  **/
  @ApiModelProperty(value = "数据")
  public List<ApiHouseResult> getData() {
    return data;
  }

  public void setData(List<ApiHouseResult> data) {
    this.data = data;
  }

  public HouseRentResponse totalNum(Integer totalNum) {
    this.totalNum = totalNum;
    return this;
  }

   /**
   * 总数
   * @return totalNum
  **/
  @ApiModelProperty(value = "总数")
  public Integer getTotalNum() {
    return totalNum;
  }

  public void setTotalNum(Integer totalNum) {
    this.totalNum = totalNum;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HouseRentResponse houseRentResponse = (HouseRentResponse) o;
    return Objects.equals(this.data, houseRentResponse.data) &&
        Objects.equals(this.totalNum, houseRentResponse.totalNum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, totalNum);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HouseRentResponse {\n");
    
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    totalNum: ").append(toIndentedString(totalNum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

