/*
 * Spring Boot使用 Swagger2 构建RestFul API
 * 接口文档
 *
 * OpenAPI spec version: v1
 * Contact: 123456@dongfangdi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bidewu.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * HouseDropDO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-26T06:55:57.895Z")
public class HouseDropDO {
  @SerializedName("city")
  private String city = null;

  @SerializedName("cityId")
  private Integer cityId = null;

  @SerializedName("fangyuanId")
  private String fangyuanId = null;

  @SerializedName("ofCompanyEn")
  private String ofCompanyEn = null;

  public HouseDropDO city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @ApiModelProperty(value = "")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public HouseDropDO cityId(Integer cityId) {
    this.cityId = cityId;
    return this;
  }

   /**
   * Get cityId
   * @return cityId
  **/
  @ApiModelProperty(value = "")
  public Integer getCityId() {
    return cityId;
  }

  public void setCityId(Integer cityId) {
    this.cityId = cityId;
  }

  public HouseDropDO fangyuanId(String fangyuanId) {
    this.fangyuanId = fangyuanId;
    return this;
  }

   /**
   * Get fangyuanId
   * @return fangyuanId
  **/
  @ApiModelProperty(value = "")
  public String getFangyuanId() {
    return fangyuanId;
  }

  public void setFangyuanId(String fangyuanId) {
    this.fangyuanId = fangyuanId;
  }

  public HouseDropDO ofCompanyEn(String ofCompanyEn) {
    this.ofCompanyEn = ofCompanyEn;
    return this;
  }

   /**
   * Get ofCompanyEn
   * @return ofCompanyEn
  **/
  @ApiModelProperty(value = "")
  public String getOfCompanyEn() {
    return ofCompanyEn;
  }

  public void setOfCompanyEn(String ofCompanyEn) {
    this.ofCompanyEn = ofCompanyEn;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HouseDropDO houseDropDO = (HouseDropDO) o;
    return Objects.equals(this.city, houseDropDO.city) &&
        Objects.equals(this.cityId, houseDropDO.cityId) &&
        Objects.equals(this.fangyuanId, houseDropDO.fangyuanId) &&
        Objects.equals(this.ofCompanyEn, houseDropDO.ofCompanyEn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(city, cityId, fangyuanId, ofCompanyEn);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HouseDropDO {\n");
    
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    cityId: ").append(toIndentedString(cityId)).append("\n");
    sb.append("    fangyuanId: ").append(toIndentedString(fangyuanId)).append("\n");
    sb.append("    ofCompanyEn: ").append(toIndentedString(ofCompanyEn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

