/*
 * Spring Boot使用 Swagger2 构建RestFul API
 * 接口文档
 *
 * OpenAPI spec version: v1
 * Contact: 123456@dongfangdi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bidewu.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TouTiaoResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-26T06:55:57.895Z")
public class TouTiaoResult {
  @SerializedName("toutiaoHouseId")
  private Integer toutiaoHouseId = null;

  @SerializedName("toutiaoHouseLink")
  private String toutiaoHouseLink = null;

  public TouTiaoResult toutiaoHouseId(Integer toutiaoHouseId) {
    this.toutiaoHouseId = toutiaoHouseId;
    return this;
  }

   /**
   * 头条房产房源Id
   * @return toutiaoHouseId
  **/
  @ApiModelProperty(value = "头条房产房源Id")
  public Integer getToutiaoHouseId() {
    return toutiaoHouseId;
  }

  public void setToutiaoHouseId(Integer toutiaoHouseId) {
    this.toutiaoHouseId = toutiaoHouseId;
  }

  public TouTiaoResult toutiaoHouseLink(String toutiaoHouseLink) {
    this.toutiaoHouseLink = toutiaoHouseLink;
    return this;
  }

   /**
   * 头条房产房源链接
   * @return toutiaoHouseLink
  **/
  @ApiModelProperty(value = "头条房产房源链接")
  public String getToutiaoHouseLink() {
    return toutiaoHouseLink;
  }

  public void setToutiaoHouseLink(String toutiaoHouseLink) {
    this.toutiaoHouseLink = toutiaoHouseLink;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TouTiaoResult touTiaoResult = (TouTiaoResult) o;
    return Objects.equals(this.toutiaoHouseId, touTiaoResult.toutiaoHouseId) &&
        Objects.equals(this.toutiaoHouseLink, touTiaoResult.toutiaoHouseLink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(toutiaoHouseId, toutiaoHouseLink);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TouTiaoResult {\n");
    
    sb.append("    toutiaoHouseId: ").append(toIndentedString(toutiaoHouseId)).append("\n");
    sb.append("    toutiaoHouseLink: ").append(toIndentedString(toutiaoHouseLink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

